//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChronExQuery.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ChronExQuery.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BoilOff,Feb 18 2018  1:21PM
        ///BoilOn,Feb 18 2018  1:21PM
        ///BoilOff,Feb 18 2018  1:25PM
        ///BoilOn,Feb 18 2018  1:25PM
        ///BoilOff,Feb 18 2018  1:26PM
        ///BoilOn,Feb 18 2018  1:27PM
        ///BoilOff,Feb 18 2018  1:30PM
        ///BoilOn,Feb 18 2018  1:31PM
        ///BoilOff,Feb 18 2018  1:32PM
        ///BoilOn,Feb 18 2018  1:33PM
        ///BoilOff,Feb 18 2018  1:34PM
        ///BoilOn,Feb 18 2018  1:35PM
        ///BoilOff,Feb 18 2018  1:36PM
        ///BoilOn,Feb 18 2018  1:36PM
        ///BoilOff,Feb 18 2018  1:40PM
        ///BoilOn,Feb 18 2018  1:40PM
        ///BoilOff,Feb 18 2018  1:41PM
        ///BoilOn,Feb 18 2018  1:41PM
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BoilerEvents {
            get {
                return ResourceManager.GetString("BoilerEvents", resourceCulture);
            }
        }
    }
}
